"""BookWyrm client library."""

try:
    from importlib.metadata import version

    __version__ = version("bookwyrm")
except ImportError:
    # Fallback for Python < 3.8 or if package not installed
    __version__ = "unknown"

from .client import BookWyrmClient, BookWyrmClientError, BookWyrmAPIError
from .async_client import AsyncBookWyrmClient
from .models import (
    Text,
    Span,
    TextSpan,
    CitationRequest,
    Citation,
    CitationResponse,
    UsageInfo,
    CitationProgressUpdate,
    CitationStreamResponse,
    CitationSummaryResponse,
    CitationErrorResponse,
    StreamingCitationResponse,
    SummarizeRequest,
    SummaryResponse,
    SummarizeProgressUpdate,
    SummarizeErrorResponse,
    RateLimitMessage,
    StructuralErrorMessage,
    StreamingSummarizeResponse,
    ProcessTextRequest,
    ResponseFormat,
    ContentEncoding,
    ModelStrength,
    PhraseProgressUpdate,
    TextResult,
    TextSpanResult,
    StreamingPhrasalResponse,
    ClassifyRequest,
    ClassifyResponse,
    StreamingClassifyResponse,
    ClassifyProgressUpdate,
    ClassifyStreamResponse,
    ClassifyErrorResponse,
    FileClassification,
    PDFExtractRequest,
    PDFExtractResponse,
    StreamingPDFResponse,
    PDFStreamMetadata,
    PDFStreamPageResponse,
    PDFStreamPageError,
    PDFStreamComplete,
    PDFStreamError,
    PDFTextElement,
    PDFPage,
    PDFStructuredData,
    PDFBoundingBox,
    CharacterMapping,
    PDFTextMapping,
)
from .utils import (
    load_chunks_from_jsonl,
    load_phrases_from_jsonl,
    load_jsonl_content,
    save_citations_to_json,
    append_citation_to_jsonl,
    pdf_to_text_with_mapping,
    pdf_to_text_with_mapping_from_json,
    create_pdf_text_mapping_from_pages,
    query_character_range,
    query_character_range_from_mapping,
    query_mapping_range_in_memory,
    save_character_query,
    save_character_query_from_mapping,
    save_mapping_query_in_memory,
)

__all__ = [
    "BookWyrmClient",
    "AsyncBookWyrmClient",
    "BookWyrmClientError",
    "BookWyrmAPIError",
    "Text",
    "Span",
    "TextSpan",
    "CitationRequest",
    "Citation",
    "CitationResponse",
    "UsageInfo",
    "CitationProgressUpdate",
    "CitationStreamResponse",
    "CitationSummaryResponse",
    "CitationErrorResponse",
    "StreamingCitationResponse",
    "SummarizeRequest",
    "SummaryResponse",
    "SummarizeProgressUpdate",
    "SummarizeErrorResponse",
    "RateLimitMessage",
    "StructuralErrorMessage",
    "StreamingSummarizeResponse",
    "ProcessTextRequest",
    "ResponseFormat",
    "ContentEncoding",
    "ModelStrength",
    "PhraseProgressUpdate",
    "TextResult",
    "TextSpanResult",
    "StreamingPhrasalResponse",
    "ClassifyRequest",
    "ClassifyResponse",
    "StreamingClassifyResponse",
    "ClassifyProgressUpdate",
    "ClassifyStreamResponse",
    "ClassifyErrorResponse",
    "FileClassification",
    "PDFExtractRequest",
    "PDFExtractResponse",
    "StreamingPDFResponse",
    "PDFStreamMetadata",
    "PDFStreamPageResponse",
    "PDFStreamPageError",
    "PDFStreamComplete",
    "PDFStreamError",
    "PDFTextElement",
    "PDFPage",
    "PDFStructuredData",
    "PDFBoundingBox",
    "CharacterMapping",
    "PDFTextMapping",
    # Utility functions
    "load_chunks_from_jsonl",
    "load_phrases_from_jsonl",
    "load_jsonl_content",
    "save_citations_to_json",
    "append_citation_to_jsonl",
    "pdf_to_text_with_mapping",
    "pdf_to_text_with_mapping_from_json",
    "create_pdf_text_mapping_from_pages",
    "query_character_range",
    "query_character_range_from_mapping",
    "query_mapping_range_in_memory",
    "save_character_query",
    "save_character_query_from_mapping",
    "save_mapping_query_in_memory",
]
